CREATE TABLE IF NOT EXISTS draw_libraries (
  id           TEXT PRIMARY KEY DEFAULT ('lib_' || lower(hex(randomblob(8)))),
  tenant_id    TEXT NOT NULL DEFAULT 'tenant_sam_primeaux',
  slug         TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  filename     TEXT NOT NULL UNIQUE,
  category     TEXT NOT NULL DEFAULT 'General',
  icon         TEXT NOT NULL DEFAULT 'package',
  r2_bucket    TEXT NOT NULL DEFAULT 'agent-sam',
  r2_key       TEXT NOT NULL,
  public_url   TEXT NOT NULL,
  file_size_bytes  INTEGER DEFAULT 0,
  item_count       INTEGER DEFAULT 0,
  is_active        INTEGER NOT NULL DEFAULT 1,
  sort_order       INTEGER NOT NULL DEFAULT 0,
  auto_load        INTEGER NOT NULL DEFAULT 0,
  agent_tags       TEXT DEFAULT '[]',
  description      TEXT,
  created_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at   INTEGER NOT NULL DEFAULT (unixepoch())
);

INSERT OR IGNORE INTO draw_libraries (slug, name, filename, category, icon, r2_key, public_url, file_size_bytes, auto_load, agent_tags) VALUES
  ('uml-er',            'UML / ER',                      'UML-ER-library.excalidrawlib',                                       'Architecture',   'diagram',   '__tools__/draw/UML-ER-library.excalidrawlib',                                       'https://tools.inneranimalmedia.com/draw/UML-ER-library.excalidrawlib',                                       125985,  1, '["uml","er","database","schema"]'),
  ('algorithms-ds',     'Algorithms and Data Structures', 'algorithms-and-data-structures-arrays-matrices-trees.excalidrawlib', 'Data Structures','tree',      '__tools__/draw/algorithms-and-data-structures-arrays-matrices-trees.excalidrawlib', 'https://tools.inneranimalmedia.com/draw/algorithms-and-data-structures-arrays-matrices-trees.excalidrawlib',  438692,  0, '["algorithms","data-structures","trees","arrays"]'),
  ('arch-components',   'Architecture Components',        'architecture-diagram-components.excalidrawlib',                      'Architecture',   'blocks',    '__tools__/draw/architecture-diagram-components.excalidrawlib',                      'https://tools.inneranimalmedia.com/draw/architecture-diagram-components.excalidrawlib',                       100464,  0, '["architecture","components","diagram"]'),
  ('architecture',      'Architecture',                   'architecture.excalidrawlib',                                         'Architecture',   'blueprint', '__tools__/draw/architecture.excalidrawlib',                                          'https://tools.inneranimalmedia.com/draw/architecture.excalidrawlib',                                          380313,  0, '["architecture","system"]'),
  ('awesome-icons',     'Awesome Icons',                  'awesome-icons.excalidrawlib',                                        'Icons',          'star',      '__tools__/draw/awesome-icons.excalidrawlib',                                         'https://tools.inneranimalmedia.com/draw/awesome-icons.excalidrawlib',                                         109588,  0, '["icons","fontawesome"]'),
  ('aws-lite',          'AWS Icons Lite',                 'aws-architecture-icons (1).excalidrawlib',                           'Cloud',          'cloud',     '__tools__/draw/aws-architecture-icons (1).excalidrawlib',                            'https://tools.inneranimalmedia.com/draw/aws-architecture-icons%20(1).excalidrawlib',                           44237,   0, '["aws","cloud","amazon"]'),
  ('aws-full',          'AWS Icons Full',                 'aws-architecture-icons.excalidrawlib',                               'Cloud',          'cloud',     '__tools__/draw/aws-architecture-icons.excalidrawlib',                                'https://tools.inneranimalmedia.com/draw/aws-architecture-icons.excalidrawlib',                               4132157, 0, '["aws","cloud","amazon","full"]'),
  ('ux-wireframe',      'UX Wireframing',                 'basic-ux-wireframing-elements.excalidrawlib',                        'Wireframe',      'mobile',    '__tools__/draw/basic-ux-wireframing-elements.excalidrawlib',                         'https://tools.inneranimalmedia.com/draw/basic-ux-wireframing-elements.excalidrawlib',                          233349,  0, '["wireframe","ux","ui","mobile"]'),
  ('cloud',             'Cloud',                          'cloud.excalidrawlib',                                                'Cloud',          'cloud',     '__tools__/draw/cloud.excalidrawlib',                                                 'https://tools.inneranimalmedia.com/draw/cloud.excalidrawlib',                                                  429095,  0, '["cloud","infrastructure"]'),
  ('data-viz',          'Data Visualization',             'data-viz.excalidrawlib',                                             'Data',           'chart',     '__tools__/draw/data-viz.excalidrawlib',                                              'https://tools.inneranimalmedia.com/draw/data-viz.excalidrawlib',                                               964925,  0, '["charts","graphs","data","visualization"]'),
  ('decision-flow',     'Decision / Flow Control',        'decision-flow-control.excalidrawlib',                                'Flow',           'flow',      '__tools__/draw/decision-flow-control.excalidrawlib',                                 'https://tools.inneranimalmedia.com/draw/decision-flow-control.excalidrawlib',                                   90235,   1, '["flow","decision","control","process"]'),
  ('deep-learning',     'Deep Learning',                  'deep-learning.excalidrawlib',                                        'AI / ML',        'neural',    '__tools__/draw/deep-learning.excalidrawlib',                                         'https://tools.inneranimalmedia.com/draw/deep-learning.excalidrawlib',                                         1122304, 0, '["ai","ml","neural","deep-learning"]'),
  ('devops',            'DevOps',                         'dev_ops.excalidrawlib',                                              'DevOps',         'gear',      '__tools__/draw/dev_ops.excalidrawlib',                                               'https://tools.inneranimalmedia.com/draw/dev_ops.excalidrawlib',                                                903587,  0, '["devops","ci","cd","pipeline"]'),
  ('drwnio',            'Drwn.io',                        'drwnio.excalidrawlib',                                               'General',        'pen',       '__tools__/draw/drwnio.excalidrawlib',                                                'https://tools.inneranimalmedia.com/draw/drwnio.excalidrawlib',                                                 188887,  0, '["general","mixed"]'),
  ('gantt',             'Gantt',                          'gantt.excalidrawlib',                                                'Planning',       'calendar',  '__tools__/draw/gantt.excalidrawlib',                                                 'https://tools.inneranimalmedia.com/draw/gantt.excalidrawlib',                                                   38717,   0, '["gantt","timeline","planning","project"]'),
  ('google-icons',      'Google Icons',                   'google-icons.excalidrawlib',                                         'Icons',          'circle',    '__tools__/draw/google-icons.excalidrawlib',                                          'https://tools.inneranimalmedia.com/draw/google-icons.excalidrawlib',                                          5160960, 0, '["google","icons","material"]'),
  ('icons',             'Icons',                          'icons.excalidrawlib',                                                'Icons',          'palette',   '__tools__/draw/icons.excalidrawlib',                                                 'https://tools.inneranimalmedia.com/draw/icons.excalidrawlib',                                                  732569,  0, '["icons","general"]'),
  ('lofi-wireframe',    'Lo-Fi Wireframing',              'lo-fi-wireframing-kit.excalidrawlib',                                'Wireframe',      'frame',     '__tools__/draw/lo-fi-wireframing-kit.excalidrawlib',                                 'https://tools.inneranimalmedia.com/draw/lo-fi-wireframing-kit.excalidrawlib',                                   261000,  0, '["wireframe","lofi","sketch","ux"]'),
  ('network-topology',  'Network Topology',               'network-topology-icons.excalidrawlib',                               'Network',        'network',   '__tools__/draw/network-topology-icons.excalidrawlib',                                'https://tools.inneranimalmedia.com/draw/network-topology-icons.excalidrawlib',                                  146367,  0, '["network","topology","infrastructure"]'),
  ('software-arch',     'Software Architecture',          'software-architecture.excalidrawlib',                                'Architecture',   'code',      '__tools__/draw/software-architecture.excalidrawlib',                                 'https://tools.inneranimalmedia.com/draw/software-architecture.excalidrawlib',                                    45660,   1, '["software","architecture","system"]'),
  ('stick-figures',     'Stick Figures',                  'stick-figures.excalidrawlib',                                        'General',        'person',    '__tools__/draw/stick-figures.excalidrawlib',                                         'https://tools.inneranimalmedia.com/draw/stick-figures.excalidrawlib',                                            95355,   0, '["people","actors","stick","figures"]'),
  ('system-design-tpl', 'System Design Template',         'system-design-template.excalidrawlib',                               'Architecture',   'template',  '__tools__/draw/system-design-template.excalidrawlib',                                'https://tools.inneranimalmedia.com/draw/system-design-template.excalidrawlib',                                  187597,  0, '["system","design","template"]'),
  ('system-design',     'System Design',                  'system-design.excalidrawlib',                                        'Architecture',   'server',    '__tools__/draw/system-design.excalidrawlib',                                         'https://tools.inneranimalmedia.com/draw/system-design.excalidrawlib',                                           223338,  0, '["system","design","architecture"]');

CREATE INDEX IF NOT EXISTS idx_draw_libraries_category ON draw_libraries(category);
CREATE INDEX IF NOT EXISTS idx_draw_libraries_active   ON draw_libraries(is_active);
