name = "inneranimalmedia-mcp-server"
main = "src/index.js"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]

# This locks deploys to the correct worker — do not change the name field

workers_dev = true
preview_urls = true

[[routes]]
pattern = "mcp.inneranimalmedia.com"
zone_name = "inneranimalmedia.com"
custom_domain = true

[[tail_consumers]]
service = "inneranimalmedia-tail"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "inneranimalmedia-assets"

[[r2_buckets]]
binding = "R2"
bucket_name = "iam-platform"

[[d1_databases]]
binding = "DB"
database_name = "inneranimalmedia-business"
database_id = "cf87b717-d4e2-4cf8-bab0-a81268e32d49"
