-- 184: System B ledger rows documenting IAM workspace shell + TOOLS R2 publish (2026-03-31).
-- Does NOT use System A (workflows / workflow_executions).
-- Idempotent: safe to re-run; replaces fixed-id documentation run/steps/artifact only.
--
-- Apply prod:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/184_system_b_iam_workspace_shell_ledger.sql
--
-- Note: remote D1 execute rejects BEGIN TRANSACTION; statements run in one batch.

-- 1) Workflow definition (typed runs; FK target for workflow_runs.workflow_id)
INSERT OR IGNORE INTO mcp_workflows (
  id,
  tenant_id,
  name,
  description,
  category,
  trigger_type,
  trigger_config_json,
  steps_json,
  timeout_seconds,
  requires_approval,
  estimated_cost_usd,
  status,
  run_count,
  success_count,
  created_at,
  updated_at
) VALUES (
  'wf_agent_code_promotion',
  'tenant_sam_primeaux',
  'Agent code promotion',
  'Agent artifact lands in TOOLS code/; optional approval; copy to agent-sam-sandbox-cidi; promote to agent-sam. Ledger: workflow_runs, workflow_steps, workflow_artifacts.',
  'agent_pipeline',
  'manual',
  '{}',
  '[
    {"name":"write_tools","step_key":"write_tools","description":"r2_write or repo path under dashboard/ / tools bucket TOOLS"},
    {"name":"await_approval","step_key":"await_approval","description":"Human gate before sandbox"},
    {"name":"r2_sandbox","step_key":"r2_sandbox","description":"Upload to agent-sam-sandbox-cidi for validation"},
    {"name":"r2_prod","step_key":"r2_prod","description":"Promote to agent-sam + worker per CIDI"}
  ]',
  7200,
  1,
  0,
  'active',
  0,
  0,
  unixepoch(),
  unixepoch()
);

-- 2) One run documenting this Cursor deliverable (no chat session; input_data carries context)
INSERT OR REPLACE INTO workflow_runs (
  id,
  tenant_id,
  workflow_id,
  workflow_name,
  workflow_type,
  trigger_source,
  triggered_by,
  status,
  steps_total,
  steps_completed,
  current_step,
  output_summary,
  cost_usd,
  ai_tokens_used,
  duration_ms,
  input_data,
  metadata_json,
  environment,
  started_at,
  completed_at,
  created_at,
  updated_at
) VALUES (
  'wfr_doc_iam_workspace_shell_20260331',
  'tenant_sam_primeaux',
  'wf_agent_code_promotion',
  'wf_agent_code_promotion',
  'code_artifact',
  'manual',
  'cursor_agent',
  'paused',
  4,
  3,
  'r2_sandbox',
  'dashboard/iam-workspace-shell.html: cms_themes solarized-dark via GET /api/settings/theme?slug=solarized-dark; published to tools/code/iam-workspace-shell.html. Sandbox R2 copy not done.',
  0,
  0,
  NULL,
  '{"dashboard_file":"dashboard/iam-workspace-shell.html","cms_theme_slug":"solarized-dark","theme_api":"GET /api/settings/theme?slug=solarized-dark","r2_bucket":"tools","r2_key":"code/iam-workspace-shell.html","public_url":"https://tools.inneranimalmedia.com/code/iam-workspace-shell.html","conversation_id":null,"agentsam_agent_run_id":null,"ledger_note":"migration_184_system_b"}',
  '{"system":"B","migration":"184"}',
  'production',
  datetime('now'),
  NULL,
  datetime('now'),
  datetime('now')
);

DELETE FROM workflow_steps WHERE run_id = 'wfr_doc_iam_workspace_shell_20260331';

INSERT INTO workflow_steps (
  id,
  run_id,
  step_number,
  step_name,
  step_type,
  status,
  started_at,
  completed_at,
  duration_ms,
  cost_usd,
  tokens_used,
  tokens_in,
  tokens_out,
  input_data,
  output_summary,
  tool_name,
  model_key,
  provider,
  created_at,
  updated_at
) VALUES
(
  'wfs_iam_ws_20260331_01',
  'wfr_doc_iam_workspace_shell_20260331',
  1,
  'write_tools',
  'execution',
  'success',
  unixepoch(),
  unixepoch(),
  NULL,
  0,
  0,
  0,
  0,
  '{"kind":"repo_file","path":"dashboard/iam-workspace-shell.html"}',
  'Workspace shell HTML authored; System B slots + solarized-dark theme fetch pattern.',
  NULL,
  NULL,
  NULL,
  unixepoch(),
  unixepoch()
),
(
  'wfs_iam_ws_20260331_02',
  'wfr_doc_iam_workspace_shell_20260331',
  2,
  'cms_theme_wire',
  'execution',
  'success',
  unixepoch(),
  unixepoch(),
  NULL,
  0,
  0,
  0,
  0,
  '{"slug":"solarized-dark","source":"cms_themes.config.cssVars"}',
  'Shell uses data-theme=solarized-dark and loads variables from DB-driven theme API.',
  NULL,
  NULL,
  NULL,
  unixepoch(),
  unixepoch()
),
(
  'wfs_iam_ws_20260331_03',
  'wfr_doc_iam_workspace_shell_20260331',
  3,
  'r2_tools_publish',
  'execution',
  'success',
  unixepoch(),
  unixepoch(),
  NULL,
  0,
  0,
  0,
  0,
  '{"binding":"TOOLS","bucket":"tools","key":"code/iam-workspace-shell.html","content_type":"text/html"}',
  'Object put to R2 tools bucket; public URL on tools.inneranimalmedia.com.',
  'wrangler_r2_object_put',
  NULL,
  NULL,
  unixepoch(),
  unixepoch()
),
(
  'wfs_iam_ws_20260331_04',
  'wfr_doc_iam_workspace_shell_20260331',
  4,
  'r2_sandbox',
  'execution',
  'pending',
  NULL,
  NULL,
  NULL,
  0,
  0,
  0,
  0,
  '{"target_bucket":"agent-sam-sandbox-cidi"}',
  NULL,
  NULL,
  NULL,
  NULL,
  unixepoch(),
  unixepoch()
);

DELETE FROM workflow_artifacts WHERE id = 'wa_iam_workspace_shell_20260331';

INSERT INTO workflow_artifacts (
  id,
  run_id,
  step_id,
  artifact_type,
  artifact_name,
  file_name,
  r2_bucket,
  r2_key,
  r2_url,
  mime_type,
  description,
  is_sensitive,
  created_at,
  updated_at,
  app_id
) VALUES (
  'wa_iam_workspace_shell_20260331',
  'wfr_doc_iam_workspace_shell_20260331',
  'wfs_iam_ws_20260331_03',
  'workspace_shell_html',
  'IAM workspace shell v0',
  'iam-workspace-shell.html',
  'tools',
  'code/iam-workspace-shell.html',
  'https://tools.inneranimalmedia.com/code/iam-workspace-shell.html',
  'text/html',
  'System B workflow_artifacts row: TOOLS code/ object; status in_tools until sandbox copy.',
  0,
  unixepoch(),
  unixepoch(),
  'app_inneranimalmedia'
);
