-- 206: AITesting playground — workers, worker_registry, workspaces (ws_aitestsandbox), settings, project.
-- Worker URL: https://aitesting.meauxbility.workers.dev (TOOLS R2 bind; no secrets in D1).
-- Apply prod:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/206_ws_aitestsandbox_aitesting_worker.sql

INSERT OR IGNORE INTO workers (
  id,
  tenant_id,
  name,
  script_name,
  status,
  requests,
  created_at,
  updated_at,
  hyperdrive_id
) VALUES (
  'aitesting',
  'tenant_sam_primeaux',
  'AITesting TOOLS playground',
  'aitesting',
  'active',
  0,
  unixepoch(),
  unixepoch(),
  NULL
);

INSERT OR REPLACE INTO worker_registry (
  id,
  worker_name,
  worker_type,
  domain_id,
  project_id,
  client_id,
  script_name,
  routes,
  bindings_count,
  bindings_detail,
  last_deployment,
  deployment_status,
  requests_30d,
  avg_cpu_ms,
  git_repo,
  last_commit_message,
  days_since_deploy,
  priority,
  monthly_cost_estimate,
  notes,
  created_at,
  updated_at,
  d1_databases,
  r2_buckets,
  r2_s3_url,
  tenant_id,
  hyperdrive_id,
  account_id,
  workers_dev_subdomain,
  zone_id,
  entity_status
) VALUES (
  'wr_aitesting_sandbox',
  'aitesting',
  'staging',
  NULL,
  NULL,
  NULL,
  'aitesting',
  'aitesting.meauxbility.workers.dev/*',
  1,
  '{"r2":["TOOLS"],"vars":["R2_PUBLIC_HOST"],"compatibility":["nodejs_compat"]}',
  unixepoch(),
  'active',
  0,
  NULL,
  NULL,
  NULL,
  NULL,
  'medium',
  0,
  'Public read of tools R2 bucket; /api/ls and /api/file. Local OpenAI codegen: set OPENAI_API_KEY in shell only — never store API keys in D1.',
  unixepoch(),
  unixepoch(),
  NULL,
  '["tools"]',
  NULL,
  'tenant_sam_primeaux',
  NULL,
  'ede6590ac0d2fb7daf155b35653457b2',
  'aitesting.meauxbility.workers.dev',
  NULL,
  'active'
);

INSERT OR IGNORE INTO workspaces (
  id,
  name,
  domain,
  category,
  status,
  cloudflare_plan,
  dns_records_count,
  workers_pages_count,
  logo_url,
  accent_color,
  created_at,
  handle,
  is_system,
  is_archived,
  owner_tenant_id,
  default_tenant_id,
  updated_at,
  theme_id,
  app_id
) VALUES (
  'ws_aitestsandbox',
  'AITesting sandbox workspace',
  'https://aitesting.meauxbility.workers.dev',
  'entity',
  'active',
  NULL,
  0,
  1,
  NULL,
  NULL,
  datetime('now'),
  'iam_aitestsandbox',
  0,
  0,
  'tenant_sam_primeaux',
  'tenant_sam_primeaux',
  datetime('now'),
  'theme-solarized-dark',
  NULL
);

INSERT OR REPLACE INTO workspace_settings (
  workspace_id,
  theme_id,
  accent_color,
  timezone,
  locale,
  settings_json,
  updated_at
) VALUES (
  'ws_aitestsandbox',
  'theme-solarized-dark',
  NULL,
  'America/Chicago',
  'en-US',
  '{"toolsPublicOrigin":"https://tools.inneranimalmedia.com","toolsR2Bucket":"tools","aitestingWorkerUrl":"https://aitesting.meauxbility.workers.dev","iamWorkspaceShellR2Key":"code/iam-workspace-shell.html","iamDocsIndexR2Key":"code/iam-docs-index.html","openaiKeyStorage":"env_only"}',
  unixepoch()
);

INSERT OR IGNORE INTO workspace_projects (
  id,
  workspace_id,
  tenant_id,
  owner_user_id,
  agent_ai_id,
  name,
  slug,
  description,
  client_company,
  project_type,
  status,
  budget_usd,
  metadata_json,
  created_at,
  updated_at
) VALUES (
  'wp_aitestsandbox_tools_playground',
  'ws_aitestsandbox',
  'tenant_sam_primeaux',
  'usr_sam_primeaux',
  'ai_sam_v1',
  'AITesting TOOLS playground',
  'aitesting-tools-playground',
  'Workers.dev mirror of tools R2; listing API for Monaco/codegen iteration.',
  'Inner Animal Media',
  'internal',
  'active',
  0,
  '{"worker_registry_id":"wr_aitesting_sandbox","workers_table_id":"aitesting","r2_bucket":"tools"}',
  unixepoch(),
  unixepoch()
);
