-- 222: commands — upload session/deploy docs to autorag (same script as agent_commands sync-session-autorag)
-- Run:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/222_commands_table_sync_session_autorag.sql

INSERT OR REPLACE INTO commands (
  id,
  tenant_id,
  tool,
  command_name,
  command_template,
  description,
  category,
  subcategory,
  tags,
  when_to_use,
  expected_output,
  is_favorite,
  usage_count,
  last_used_at,
  created_by,
  created_at,
  updated_at,
  is_slash_command,
  provider,
  requires_confirmation,
  cost_tier,
  output_type,
  is_system,
  version
) VALUES (
  'cmd_upload_session_autorag',
  'tenant_sam_primeaux',
  'bash',
  'Upload session log snapshot to autorag R2',
  './scripts/upload-session-docs-to-autorag.sh',
  'Puts knowledge/workflows/iam-deploy-promote-and-session-log-rag.md and context/cursor-session-log-recent.md into the autorag bucket for RAG. Run after editing docs/cursor-session-log.md; then ingest into D1 RAG if applicable.',
  'deployment',
  'rag',
  'autorag,rag,session-log,docs',
  'After appending to docs/cursor-session-log.md or before relying on RAG for deploy/session answers.',
  'Wrangler upload complete; two keys under autorag/knowledge/... and autorag/context/...',
  0,
  0,
  NULL,
  'sam_primeaux',
  unixepoch(),
  unixepoch(),
  0,
  'system',
  0,
  'free',
  'text',
  1,
  '1.0'
);
