-- 249: integration_catalog — seeded reference rows (matches prod D1 as of 2026-05-01).
-- Apply: ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/249_integration_catalog.sql

CREATE TABLE IF NOT EXISTS integration_catalog (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL CHECK(category IN (
    'ai_provider','storage','communication','source_control',
    'database','calendar','analytics','payment','custom','iam_hosted'
  )),
  auth_type TEXT NOT NULL CHECK(auth_type IN ('oauth','api_key','oauth_or_key','none')),
  oauth_authorize_url TEXT,
  oauth_scopes_default TEXT DEFAULT '[]',
  oauth_scopes_available TEXT DEFAULT '[]',
  api_key_label TEXT,
  api_key_placeholder TEXT,
  docs_url TEXT,
  icon_slug TEXT,
  description TEXT,
  is_active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 50,
  created_at INTEGER DEFAULT (unixepoch())
);

INSERT OR REPLACE INTO integration_catalog (
  id, name, slug, category, auth_type, oauth_authorize_url,
  oauth_scopes_default, oauth_scopes_available,
  api_key_label, api_key_placeholder, docs_url, icon_slug, description,
  is_active, sort_order, created_at
) VALUES
(
  'iam_agentsam',
  'Agent Sam MCP',
  'agentsam',
  'iam_hosted',
  'none',
  NULL,
  '[]',
  '[]',
  NULL,
  NULL,
  'https://mcp.inneranimalmedia.com/mcp',
  'agentsam',
  'InnerAnimal Media core tools — D1, R2, terminal, deployments, workflows',
  1,
  1,
  1777675015
),
(
  'iam_autodidact',
  'InnerAutodidact MCP',
  'autodidact',
  'iam_hosted',
  'none',
  NULL,
  '[]',
  '[]',
  NULL,
  NULL,
  'https://mcp.inneranimalmedia.com/mcp',
  'autodidact',
  'Learning platform tools — courses, assignments, progress tracking',
  1,
  2,
  1777675015
),
(
  'cloudflare',
  'Cloudflare',
  'cloudflare',
  'storage',
  'oauth',
  'https://dash.cloudflare.com/oauth2/auth',
  '["account:read","d1:read","r2:read","workers:read"]',
  '["account:read","account:write","d1:read","d1:write","r2:read","r2:write","workers:read","workers:write","kv:read","kv:write","images:read","stream:read","pages:read"]',
  NULL,
  NULL,
  'https://developers.cloudflare.com/fundamentals/api/get-started/create-token/',
  'cloudflare',
  'Connect your Cloudflare account — R2, D1, Workers, KV, Images, Stream',
  1,
  10,
  1777675015
),
(
  'google_drive',
  'Google Drive',
  'google-drive',
  'storage',
  'oauth',
  'https://accounts.google.com/o/oauth2/auth',
  '["https://www.googleapis.com/auth/drive.readonly"]',
  '["https://www.googleapis.com/auth/drive.readonly","https://www.googleapis.com/auth/drive.file"]',
  NULL,
  NULL,
  'https://developers.google.com/drive',
  'google-drive',
  'Access your Google Drive files and folders',
  1,
  20,
  1777675015
),
(
  'gmail',
  'Gmail',
  'gmail',
  'communication',
  'oauth',
  'https://accounts.google.com/o/oauth2/auth',
  '["https://www.googleapis.com/auth/gmail.readonly"]',
  '["https://www.googleapis.com/auth/gmail.readonly","https://www.googleapis.com/auth/gmail.send","https://www.googleapis.com/auth/gmail.modify"]',
  NULL,
  NULL,
  'https://developers.google.com/gmail/api',
  'gmail',
  'Read and send emails via Agent Sam',
  1,
  21,
  1777675015
),
(
  'google_calendar',
  'Google Calendar',
  'google-calendar',
  'calendar',
  'oauth',
  'https://accounts.google.com/o/oauth2/auth',
  '["https://www.googleapis.com/auth/calendar.readonly"]',
  '["https://www.googleapis.com/auth/calendar.readonly","https://www.googleapis.com/auth/calendar.events"]',
  NULL,
  NULL,
  'https://developers.google.com/calendar',
  'google-calendar',
  'View and create calendar events',
  1,
  22,
  1777675015
),
(
  'github',
  'GitHub',
  'github',
  'source_control',
  'oauth',
  'https://github.com/login/oauth/authorize',
  '["repo:read","user:read"]',
  '["repo","repo:read","public_repo","user","read:org","workflow"]',
  NULL,
  NULL,
  'https://docs.github.com/en/apps/oauth-apps',
  'github',
  'Repos, issues, actions, deployments',
  1,
  30,
  1777675015
),
(
  'supabase',
  'Supabase',
  'supabase',
  'database',
  'oauth_or_key',
  'https://api.supabase.com/v1/oauth/authorize',
  '["database.read"]',
  '["database.read","database.write","storage.read","storage.write","edge_functions.read"]',
  'Service Role Key',
  'sbp_...',
  'https://supabase.com/docs/guides/api',
  'supabase',
  'Postgres, Storage, Edge Functions',
  1,
  40,
  1777675015
),
(
  'resend',
  'Resend',
  'resend',
  'communication',
  'api_key',
  NULL,
  '[]',
  '[]',
  'API Key',
  're_...',
  'https://resend.com/docs',
  'resend',
  'Send transactional emails using your Resend account',
  1,
  50,
  1777675015
),
(
  'stripe',
  'Stripe',
  'stripe',
  'payment',
  'oauth_or_key',
  'https://connect.stripe.com/oauth/authorize',
  '["read_only"]',
  '["read_only"]',
  'Secret Key',
  'sk_live_...',
  'https://stripe.com/docs/connect',
  'stripe',
  'View your Stripe revenue, customers, and invoices',
  1,
  60,
  1777675015
),
(
  'anthropic',
  'Anthropic Claude',
  'anthropic',
  'ai_provider',
  'api_key',
  NULL,
  '[]',
  '[]',
  'API Key',
  'sk-ant-...',
  'https://docs.anthropic.com/en/api',
  'anthropic',
  'Use your own Anthropic key — full model access billed to your account',
  1,
  70,
  1777675015
),
(
  'openai',
  'OpenAI',
  'openai',
  'ai_provider',
  'api_key',
  NULL,
  '[]',
  '[]',
  'API Key',
  'sk-...',
  'https://platform.openai.com/docs',
  'openai',
  'GPT-4o, o1, DALL-E, Whisper — billed to your OpenAI account',
  1,
  71,
  1777675015
),
(
  'google_ai',
  'Google AI (Gemini)',
  'google-ai',
  'ai_provider',
  'oauth_or_key',
  'https://accounts.google.com/o/oauth2/auth',
  '["https://www.googleapis.com/auth/generative-language"]',
  '["https://www.googleapis.com/auth/generative-language","https://www.googleapis.com/auth/cloud-platform"]',
  'API Key',
  'AIza...',
  'https://ai.google.dev/gemini-api/docs',
  'google-ai',
  'Gemini models via your own Google AI account',
  1,
  72,
  1777675015
),
(
  'custom_mcp',
  'Custom MCP Server',
  'custom-mcp',
  'custom',
  'oauth_or_key',
  NULL,
  '[]',
  '[]',
  'Bearer Token (optional)',
  'Bearer ...',
  'https://modelcontextprotocol.io/docs',
  'custom',
  'Connect any MCP-compatible server with your own tools',
  1,
  99,
  1777675015
);
