-- One-off: catalog row for Cursor Composer 2 sessions (InnerAnimalMedia Agent Sam / IAM SaaS).
-- Not an API-callable LLM; show_in_picker=0 so dashboard chat does not offer it as a completion target.
-- Applied to production D1 via wrangler 2026-03-22.

INSERT INTO ai_models (
  id,
  provider,
  model_key,
  display_name,
  billing_unit,
  context_default_tokens,
  context_max_tokens,
  supports_cache,
  supports_tools,
  supports_vision,
  supports_web_search,
  supports_fast_mode,
  size_class,
  is_active,
  metadata_json,
  created_at,
  updated_at,
  input_rate_per_mtok,
  output_rate_per_mtok,
  cache_write_rate_per_mtok,
  cache_read_rate_per_mtok,
  web_search_per_1k_usd,
  neurons_usd_per_1k,
  pricing_source,
  show_in_picker,
  secret_key_name
) VALUES (
  'composer2-agentsam',
  'cursor',
  'composer2-agentsam',
  'Cursor Composer 2 (InnerAnimalMedia Agent Sam)',
  'tokens',
  0,
  200000,
  0,
  1,
  0,
  0,
  0,
  'medium',
  1,
  '{"user_agent_label":"composer2_agentsam","product":"InnerAnimalMedia","saas":"Agent Sam dashboard","role":"IDE agent session"}',
  unixepoch(),
  unixepoch(),
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  0,
  'cursor_composer',
  0,
  NULL
);
