-- Backfill dashboard_assets from verified R2 metadata (Cloudflare API list).
-- Database: inneranimalmedia-business (D1)
-- Already applied to production remote 2026-03-24. Re-run is safe (INSERT OR IGNORE).
-- Run:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./scripts/d1-backfill-dashboard_assets-20260324.sql
--
-- Includes:
-- - 13 dashboard HTML pages under agent-sam static/dashboard/ (sizes from API)
-- - agent bundle JS/CSS v137 + shell.css (sizes from API / dashboard_versions)
-- - All non-empty iam-docs bucket objects (27 files; skipped zero-byte agents/ prefix key)

-- backfill dashboard_assets generated; INSERT OR IGNORE
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_agent', 'ws_inneranimal', 'file', 'Agent Sam Dashboard Page', 'r2', 'static/dashboard/agent.html', 'https://inneranimalmedia.com/dashboard/agent', 'text/html', 64665, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_overview', 'ws_inneranimal', 'file', 'Overview Dashboard Page', 'r2', 'static/dashboard/overview.html', 'https://inneranimalmedia.com/dashboard/overview', 'text/html', 72608, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_finance', 'ws_inneranimal', 'file', 'Finance Dashboard Page', 'r2', 'static/dashboard/finance.html', 'https://inneranimalmedia.com/dashboard/finance', 'text/html', 74818, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_billing', 'ws_inneranimal', 'file', 'Billing Dashboard Page', 'r2', 'static/dashboard/billing.html', 'https://inneranimalmedia.com/dashboard/billing', 'text/html', 80489, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_clients', 'ws_inneranimal', 'file', 'Clients Dashboard Page', 'r2', 'static/dashboard/clients.html', 'https://inneranimalmedia.com/dashboard/clients', 'text/html', 93148, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_mcp', 'ws_inneranimal', 'file', 'MCP Dashboard Page', 'r2', 'static/dashboard/mcp.html', 'https://inneranimalmedia.com/dashboard/mcp', 'text/html', 77094, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_cloud', 'ws_inneranimal', 'file', 'Cloud Dashboard Page', 'r2', 'static/dashboard/cloud.html', 'https://inneranimalmedia.com/dashboard/cloud', 'text/html', 85339, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_kanban', 'ws_inneranimal', 'file', 'Kanban Dashboard Page', 'r2', 'static/dashboard/kanban.html', 'https://inneranimalmedia.com/dashboard/kanban', 'text/html', 51159, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_cms', 'ws_inneranimal', 'file', 'CMS Dashboard Page', 'r2', 'static/dashboard/cms.html', 'https://inneranimalmedia.com/dashboard/cms', 'text/html', 103063, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_mail', 'ws_inneranimal', 'file', 'Mail Dashboard Page', 'r2', 'static/dashboard/mail.html', 'https://inneranimalmedia.com/dashboard/mail', 'text/html', 61500, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_timetracking', 'ws_inneranimal', 'file', 'Time Tracking Dashboard Page', 'r2', 'static/dashboard/time-tracking.html', 'https://inneranimalmedia.com/dashboard/time-tracking', 'text/html', 74772, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_draw', 'ws_inneranimal', 'file', 'Draw Page', 'r2', 'static/dashboard/pages/draw.html', 'https://inneranimalmedia.com/dashboard/pages/draw.html', 'text/html', 35371, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_page_usersettings', 'ws_samprimeaux', 'file', 'User Settings Page', 'r2', 'static/dashboard/user-settings.html', 'https://inneranimalmedia.com/dashboard/user-settings', 'text/html', 182827, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_bundle_agent_js_v137', 'ws_inneranimal_app', 'file', 'Agent dashboard bundle JS (v137)', 'r2', 'static/dashboard/agent/agent-dashboard.js', 'https://inneranimalmedia.com/static/dashboard/agent/agent-dashboard.js?v=137', 'application/javascript', 457608, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_bundle_agent_css_v137', 'ws_inneranimal_app', 'file', 'Agent dashboard bundle CSS (v137)', 'r2', 'static/dashboard/agent/agent-dashboard.css', 'https://inneranimalmedia.com/static/dashboard/agent/agent-dashboard.css?v=137', 'text/css', 2944, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_shell_css', 'ws_inneranimal_app', 'file', 'Dashboard shell.css', 'r2', 'static/dashboard/shell.css', 'https://inneranimalmedia.com/static/dashboard/shell.css', 'text/css', 998, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_README_md', 'ws_inneranimal', 'file', 'README.md', 'r2', 'README.md', 'https://docs.inneranimalmedia.com/README.md', 'text/markdown', 845, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_README_md', 'ws_inneranimal', 'file', 'README.md', 'r2', 'agents/README.md', 'https://docs.inneranimalmedia.com/agents/README.md', 'text/markdown', 5430, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_anthropic_md', 'ws_inneranimal', 'file', 'anthropic.md', 'r2', 'agents/anthropic.md', 'https://docs.inneranimalmedia.com/agents/anthropic.md', 'text/markdown', 4307, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_auto_mode_md', 'ws_inneranimal', 'file', 'auto-mode.md', 'r2', 'agents/auto-mode.md', 'https://docs.inneranimalmedia.com/agents/auto-mode.md', 'text/markdown', 3209, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_google_gemini_md', 'ws_inneranimal', 'file', 'google-gemini.md', 'r2', 'agents/google-gemini.md', 'https://docs.inneranimalmedia.com/agents/google-gemini.md', 'text/markdown', 3056, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_iam_docs_index_html', 'ws_inneranimal', 'file', 'iam-docs-index.html', 'r2', 'agents/iam-docs-index.html', 'https://docs.inneranimalmedia.com/agents/iam-docs-index.html', 'text/html', 26413, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_openai_md', 'ws_inneranimal', 'file', 'openai.md', 'r2', 'agents/openai.md', 'https://docs.inneranimalmedia.com/agents/openai.md', 'text/markdown', 3209, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_tool_reference_md', 'ws_inneranimal', 'file', 'tool-reference.md', 'r2', 'agents/tool-reference.md', 'https://docs.inneranimalmedia.com/agents/tool-reference.md', 'text/markdown', 5280, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_agents_workers_ai_md', 'ws_inneranimal', 'file', 'workers-ai.md', 'r2', 'agents/workers-ai.md', 'https://docs.inneranimalmedia.com/agents/workers-ai.md', 'text/markdown', 2589, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_autorag_architecture_how_rag_works_md', 'ws_inneranimal', 'file', 'how-rag-works.md', 'r2', 'autorag/architecture/how-rag-works.md', 'https://docs.inneranimalmedia.com/autorag/architecture/how-rag-works.md', 'text/markdown', 2984, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_autorag_sessions_2026_03_23_full_session_md', 'ws_inneranimal', 'file', '2026-03-23-full-session.md', 'r2', 'autorag/sessions/2026-03-23-full-session.md', 'https://docs.inneranimalmedia.com/autorag/sessions/2026-03-23-full-session.md', 'text/markdown', 3499, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_clients_README_md', 'ws_inneranimal', 'file', 'README.md', 'r2', 'clients/README.md', 'https://docs.inneranimalmedia.com/clients/README.md', 'text/markdown', 1464, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_clients_pelican_peptides_overview_md', 'ws_inneranimal', 'file', 'overview.md', 'r2', 'clients/pelican-peptides/overview.md', 'https://docs.inneranimalmedia.com/clients/pelican-peptides/overview.md', 'text/markdown', 754, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_clients_swamp_blood_gator_overview_md', 'ws_inneranimal', 'file', 'overview.md', 'r2', 'clients/swamp-blood-gator/overview.md', 'https://docs.inneranimalmedia.com/clients/swamp-blood-gator/overview.md', 'text/markdown', 595, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_cursor_CURSOR_MCP_FIX_INSTRUCTIONS_md', 'ws_inneranimal', 'file', 'CURSOR_MCP_FIX_INSTRUCTIONS.md', 'r2', 'cursor/CURSOR_MCP_FIX_INSTRUCTIONS.md', 'https://docs.inneranimalmedia.com/cursor/CURSOR_MCP_FIX_INSTRUCTIONS.md', 'text/markdown', 16951, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_cursor_IAM_CURSOR_CONTEXT_md', 'ws_inneranimal', 'file', 'IAM-CURSOR-CONTEXT.md', 'r2', 'cursor/IAM-CURSOR-CONTEXT.md', 'https://docs.inneranimalmedia.com/cursor/IAM-CURSOR-CONTEXT.md', 'text/markdown', 2685, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_iam_docs_index_html', 'ws_inneranimal', 'file', 'iam-docs-index.html', 'r2', 'iam-docs-index.html', 'https://docs.inneranimalmedia.com/iam-docs-index.html', 'text/html', 18436, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_index_html', 'ws_inneranimal', 'file', 'index.html', 'r2', 'index.html', 'https://docs.inneranimalmedia.com/index.html', 'text/html', 18436, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_platform_bindings_reference_md', 'ws_inneranimal', 'file', 'bindings-reference.md', 'r2', 'platform/bindings-reference.md', 'https://docs.inneranimalmedia.com/platform/bindings-reference.md', 'text/markdown', 3111, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_platform_d1_schema_overview_md', 'ws_inneranimal', 'file', 'd1-schema-overview.md', 'r2', 'platform/d1-schema-overview.md', 'https://docs.inneranimalmedia.com/platform/d1-schema-overview.md', 'text/markdown', 3506, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_platform_deploy_runbook_md', 'ws_inneranimal', 'file', 'deploy-runbook.md', 'r2', 'platform/deploy-runbook.md', 'https://docs.inneranimalmedia.com/platform/deploy-runbook.md', 'text/markdown', 4472, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_platform_r2_bucket_map_md', 'ws_inneranimal', 'file', 'r2-bucket-map.md', 'r2', 'platform/r2-bucket-map.md', 'https://docs.inneranimalmedia.com/platform/r2-bucket-map.md', 'text/markdown', 2886, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_platform_worker_routing_md', 'ws_inneranimal', 'file', 'worker-routing.md', 'r2', 'platform/worker-routing.md', 'https://docs.inneranimalmedia.com/platform/worker-routing.md', 'text/markdown', 4272, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_screenshots_README_md', 'ws_inneranimal', 'file', 'README.md', 'r2', 'screenshots/README.md', 'https://docs.inneranimalmedia.com/screenshots/README.md', 'text/markdown', 1978, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_assets (id, workspace_id, kind, title, storage, r2_key, url, mime, size_bytes, tags_json, is_official, created_by, created_at, updated_at) VALUES ('da_doc_sessions_README_md', 'ws_inneranimal', 'file', 'README.md', 'r2', 'sessions/README.md', 'https://docs.inneranimalmedia.com/sessions/README.md', 'text/markdown', 976, NULL, 1, 'sam_primeaux', datetime('now'), datetime('now'));
